imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    importModules:
      - '@creifenscheid/site-setup/plugins/abbreviation/plugin.js'
      - { module: '@ckeditor/ckeditor5-language', exports: [ 'TextPartLanguage' ] }

    toolbar:
      items:
        - textPartLanguage
        - abbreviation
        - '|'
        - link
        - '|'
        - alignment
        - bulletedList
        - numberedList
        - indent
        - outdent
        - '|'
        - clipboard
        - removeFormat
        - undo
        - redo
        # line break
        - '-'
        - heading
        - '|'
        - bold
        - italic
        - underline
        - strikethrough
        - subscript
        - superscript
        - '|'
        - softhyphen
        - '|'
        - sourceEditing

    alignment:
      options:
        - { name: 'left', className: 'align-left' }
        - { name: 'center', className: 'align-center' }
        - { name: 'right', className: 'align-right' }
        - { name: 'justify', className: 'align-justify' }

    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }

    language:
      textPartLanguage:
        # EXAMPLE - {title: 'arabic', languageCode: 'ar', textDirection: 'rtl'}
        - { title: 'english', languageCode: 'en' }
