imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: "./Plugins.yaml" }

editor:

  config:
    toolbar:
      - [ 'Link', 'Unlink', 'Abbr' ]
      - [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight' ]
      - [ 'BulletedList', 'NumberedList']}
      - [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', 'RemoveFormat' ]
      - [ 'Undo', 'Redo' ]
      - "/"
      - [ 'Language' ]
      - [ 'Format' ]
      - [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]
      - [ 'HorizontalRule', 'Blockquote', 'SpecialChar']
      - [ 'Source', 'Maximize' ]

    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css"]
    resize_enabled: true
    resize_dir: 'both'
    uiColor: "#F8F8F8"
    qtClass: 'content-table'

    justifyClasses: ['align-left', 'align-center', 'align-right', 'align-justify']

    extraPlugins:
      - justify
      - wordcount
      - abbr
      - language

    removePlugins:
      - image

    format_tags: "p"

processing:
  allowTags:
    - s
    - u
